spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring3_security6
    username: postgres
    password: 123
    driver: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

